# -*- coding: utf-8 -*-
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import Select
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import NoAlertPresentException
import unittest, time, re

class Cont(unittest.TestCase):
    def setUp(self):
        self.driver = webdriver.Firefox()
        self.driver.implicitly_wait(30)
        self.base_url = "http://127.0.0.1:8000/"
        self.verificationErrors = []
        self.accept_next_alert = True
    
    def test_cont(self):
        driver = self.driver
        driver.get("http://127.0.0.1:8000/")
        driver.find_element_by_xpath("//div[@id='header']/div/center").click()
        driver.find_element_by_name("username").click()
        driver.find_element_by_xpath("//a[@id='registrarse']/b").click()
        driver.find_element_by_id("id_first_name").click()
        driver.find_element_by_id("id_first_name").clear()
        driver.find_element_by_id("id_first_name").send_keys("adminis")
        driver.find_element_by_id("id_last_name").clear()
        driver.find_element_by_id("id_last_name").send_keys("trador")
        driver.find_element_by_xpath("//div[@id='cuerpoHeredado']/form/div[2]/div").click()
        driver.find_element_by_id("id_email").click()
        driver.find_element_by_id("id_email").clear()
        driver.find_element_by_id("id_email").send_keys("a")
        driver.find_element_by_id("id_email").send_keys(Keys.DOWN)
        driver.find_element_by_id("id_email").clear()
        driver.find_element_by_id("id_email").send_keys("a@gmail.com")
        driver.find_element_by_xpath("//div[@id='cuerpoHeredado']/form/div[3]/label").click()
        driver.find_element_by_id("id_rol").click()
        driver.find_element_by_xpath("//option[@value='admin']").click()
        driver.find_element_by_xpath("//div[@id='cuerpoHeredado']/form/div[4]/div").click()
        driver.find_element_by_id("id_ci").click()
        driver.find_element_by_id("id_ci").click()
        driver.find_element_by_id("id_ci").clear()
        driver.find_element_by_id("id_ci").send_keys("11111111")
        driver.find_element_by_id("id_username").click()
        driver.find_element_by_id("id_username").clear()
        driver.find_element_by_id("id_username").send_keys("administrador")
        driver.find_element_by_xpath("//div[@id='cuerpoHeredado']/form/div[5]/label").click()
        driver.find_element_by_id("id_passw").click()
        driver.find_element_by_id("id_passw").clear()
        driver.find_element_by_id("id_passw").send_keys("12345")
        driver.find_element_by_id("id_submit").click()
        driver.find_element_by_xpath("//a[@id='registrarse']/b").click()
        driver.find_element_by_id("id_first_name").click()
        driver.find_element_by_id("id_first_name").clear()
        driver.find_element_by_id("id_first_name").send_keys("pac")
        driver.find_element_by_id("id_last_name").clear()
        driver.find_element_by_id("id_last_name").send_keys("iente")
        driver.find_element_by_id("id_email").clear()
        driver.find_element_by_id("id_email").send_keys("p@gmail.com")
        driver.find_element_by_id("id_rol").click()
        Select(driver.find_element_by_id("id_rol")).select_by_visible_text("Paciente")
        driver.find_element_by_xpath("//option[@value='paciente']").click()
        driver.find_element_by_id("id_ci").click()
        driver.find_element_by_id("id_ci").clear()
        driver.find_element_by_id("id_ci").send_keys("11111112")
        driver.find_element_by_xpath("//div[@id='cuerpoHeredado']/form/div[5]/label").click()
        driver.find_element_by_id("id_username").click()
        driver.find_element_by_id("id_username").clear()
        driver.find_element_by_id("id_username").send_keys("paciente")
        driver.find_element_by_id("id_passw").clear()
        driver.find_element_by_id("id_passw").send_keys("12345")
        driver.find_element_by_id("id_submit").click()
        driver.find_element_by_xpath("//a[@id='registrarse']/b").click()
        driver.find_element_by_id("id_first_name").click()
        driver.find_element_by_id("id_first_name").clear()
        driver.find_element_by_id("id_first_name").send_keys("med")
        driver.find_element_by_id("id_last_name").clear()
        driver.find_element_by_id("id_last_name").send_keys("ico")
        driver.find_element_by_id("id_email").clear()
        driver.find_element_by_id("id_email").send_keys("m@gmail.com")
        driver.find_element_by_id("id_rol").click()
        Select(driver.find_element_by_id("id_rol")).select_by_visible_text("Medico")
        driver.find_element_by_xpath("//option[@value='medico']").click()
        driver.find_element_by_id("id_ci").click()
        driver.find_element_by_id("id_ci").clear()
        driver.find_element_by_id("id_ci").send_keys("11111113")
        driver.find_element_by_xpath("//div[@id='cuerpoHeredado']/form/div[5]").click()
        driver.find_element_by_id("id_username").click()
        driver.find_element_by_id("id_username").clear()
        driver.find_element_by_id("id_username").send_keys("medico")
        driver.find_element_by_xpath("//div[@id='cuerpoHeredado']/form/div[4]/div").click()
        driver.find_element_by_id("id_passw").click()
        driver.find_element_by_id("id_passw").clear()
        driver.find_element_by_id("id_passw").send_keys("12345")
        driver.find_element_by_xpath("//div[@id='cuerpoHeredado']/form/div[6]/div").click()
        driver.find_element_by_id("id_submit").click()
        driver.find_element_by_name("username").click()
        driver.find_element_by_name("username").clear()
        driver.find_element_by_name("username").send_keys("administrador")
        driver.find_element_by_name("password").clear()
        driver.find_element_by_name("password").send_keys("12345")
        driver.find_element_by_xpath("//input[@value='Login']").click()
        driver.find_element_by_link_text("Gestionar Usuarios").click()
        driver.find_element_by_xpath("//div[@id='show-users']/table/tbody/tr[2]/td[7]/a/i").click()
        driver.find_element_by_id("id_submit").click()
        driver.find_element_by_xpath("//div[@id='show-users']/table/tbody/tr[2]/td[7]/a/i").click()
        driver.find_element_by_id("id_first_name").click()
        driver.find_element_by_id("id_first_name").clear()
        driver.find_element_by_id("id_first_name").send_keys("pac1")
        driver.find_element_by_xpath("//div[@id='cuerpoHeredado']/form/label[3]").click()
        driver.find_element_by_id("id_submit").click()
        driver.find_element_by_id("id_first_name").clear()
        driver.find_element_by_id("id_first_name").send_keys("pac")
        driver.find_element_by_id("id_last_name").click()
        driver.find_element_by_id("id_first_name").click()
        driver.find_element_by_id("id_first_name").clear()
        driver.find_element_by_id("id_first_name").send_keys("Pac")
        driver.find_element_by_xpath("//form[@action='']").click()
        driver.find_element_by_id("id_submit").click()
        driver.find_element_by_xpath("//div[@id='show-users']/table/tbody/tr[4]/td[3]").click()
        driver.find_element_by_xpath("//div[@id='show-users']/table/tbody/tr[4]/td[3]").click()
        driver.find_element_by_link_text("Gestionar Roles").click()
        driver.find_element_by_link_text("Gestionar Instituciones").click()
        driver.find_element_by_xpath("//a[@id='add_institucion']/i").click()
        driver.find_element_by_id("id_rif").click()
        driver.find_element_by_id("id_rif").clear()
        driver.find_element_by_id("id_rif").send_keys("j-11111111")
        driver.find_element_by_id("id_name").click()
        driver.find_element_by_id("id_name").clear()
        driver.find_element_by_id("id_name").send_keys("institucion")
        driver.find_element_by_id("id_address").click()
        driver.find_element_by_id("id_address").clear()
        driver.find_element_by_id("id_address").send_keys("caracas")
        driver.find_element_by_id("id_tipo").click()
        driver.find_element_by_xpath("//option[@value='Hospital']").click()
        driver.find_element_by_id("id_tipo").click()
        Select(driver.find_element_by_id("id_tipo")).select_by_visible_text("Laboratorio")
        driver.find_element_by_xpath("//option[@value='Laboratorio']").click()
        driver.find_element_by_id("id_submit").click()
        driver.find_element_by_link_text("Gestionar Especializaciones").click()
        driver.find_element_by_xpath("//a[@id='add_appointment']/i").click()
        driver.find_element_by_id("id_nombre_especialidad").click()
        driver.find_element_by_id("id_nombre_especialidad").clear()
        driver.find_element_by_id("id_nombre_especialidad").send_keys("cardiologia")
        #driver.find_element_by_xpath("//div[@id='cuerpoHeredado']/form/div[3]/div[2]").click()
        driver.find_element_by_id("id_submit").click()
        driver.find_element_by_link_text("Gestionar Laboratorios").click()
        driver.find_element_by_xpath("//a[@id='add_laboratorio']/i").click()
        driver.find_element_by_id("id_rif").click()
        driver.find_element_by_id("id_rif").clear()
        driver.find_element_by_id("id_rif").send_keys("j-21111111")
        driver.find_element_by_id("id_name").click()
        driver.find_element_by_id("id_name").clear()
        driver.find_element_by_id("id_name").send_keys("Laboratorio")
        driver.find_element_by_id("id_address").clear()
        driver.find_element_by_id("id_address").send_keys("Caracas")
        driver.find_element_by_id("id_regent").clear()
        driver.find_element_by_id("id_regent").send_keys("Regente")
        driver.find_element_by_id("id_institucion").click()
        Select(driver.find_element_by_id("id_institucion")).select_by_visible_text("institucion")
        driver.find_element_by_id("id_submit").click()
        driver.find_element_by_xpath("//div[@id='show-laboratorios']/table/tbody/tr[2]/td[6]/a/i").click()
        driver.find_element_by_id("id_rif").click()
        driver.find_element_by_id("id_rif").clear()
        driver.find_element_by_id("id_rif").send_keys("j-21111112")
        driver.find_element_by_xpath("//div[@id='cuerpoHeredado']/form/label[3]").click()
        driver.find_element_by_id("id_submit").click()
        driver.find_element_by_link_text(u"Gestionar Tipos de Exámen").click()
        driver.find_element_by_xpath("//a[@id='add_institucion']/i").click()
        driver.find_element_by_id("id_nombretipo").click()
        driver.find_element_by_id("id_nombretipo").clear()
        driver.find_element_by_id("id_nombretipo").send_keys("colonoscopia")
        driver.find_element_by_id("id_submit").click()
        driver.find_element_by_link_text("Gestionar Mediciones").click()
        driver.find_element_by_xpath("//a[@id='add_medicion']/i").click()
        driver.find_element_by_id("id_tipoexamen").click()
        Select(driver.find_element_by_id("id_tipoexamen")).select_by_visible_text("colonoscopia")
        driver.find_element_by_xpath("//option[@value='colonoscopia']").click()
        driver.find_element_by_id("id_nombremedicion").click()
        driver.find_element_by_id("id_nombremedicion").clear()
        driver.find_element_by_id("id_nombremedicion").send_keys("medicion")
        driver.find_element_by_xpath("//div[@id='cuerpoHeredado']/form/label[2]").click()
        driver.find_element_by_id("id_unidad").click()
        driver.find_element_by_id("id_unidad").clear()
        driver.find_element_by_id("id_unidad").send_keys("gramos")
        driver.find_element_by_id("id_rangoesperado").click()
        driver.find_element_by_id("id_rangoesperado").clear()
        driver.find_element_by_id("id_rangoesperado").send_keys("10")
        driver.find_element_by_id("id_posicion").click()
        driver.find_element_by_id("id_posicion").clear()
        driver.find_element_by_id("id_posicion").send_keys("pos")
        driver.find_element_by_id("id_unidad").click()
        driver.find_element_by_id("id_rangoesperado").click()
        driver.find_element_by_id("id_rangoesperado").click()
        driver.find_element_by_id("id_rangoesperado").click()
        driver.find_element_by_id("id_rangoesperado").clear()
        driver.find_element_by_id("id_rangoesperado").send_keys("2 a 5")
        driver.find_element_by_id("cuerpoHeredado").click()
        driver.find_element_by_id("id_submit").click()
        driver.find_element_by_link_text("Salir").click()
        driver.find_element_by_name("username").click()
        driver.find_element_by_name("username").clear()
        driver.find_element_by_name("username").send_keys("medico")
        driver.find_element_by_name("password").clear()
        driver.find_element_by_name("password").send_keys("12345")
        driver.find_element_by_xpath("//input[@value='Login']").click()
        driver.find_element_by_link_text("Inbox").click()
        driver.find_element_by_link_text("Ver Perfil").click()
        driver.find_element_by_link_text("Ver Horario De Consultas").click()
        driver.find_element_by_link_text(u"Historias Clínicas").click()
        driver.find_element_by_link_text("Buscar paciente").click()
        driver.find_element_by_link_text(u"Buscar médico").click()
        driver.find_element_by_link_text("Ver Citas").click()
        driver.find_element_by_link_text("Solicitar Examen").click()
        driver.find_element_by_id("id_tipoexamen").click()
        Select(driver.find_element_by_id("id_tipoexamen")).select_by_visible_text("colonoscopia")
        driver.find_element_by_xpath("//option[@value='colonoscopia']").click()
        driver.find_element_by_id("id_laboratorio").click()
        Select(driver.find_element_by_id("id_laboratorio")).select_by_visible_text("Laboratorio")
        driver.find_element_by_id("id_paciente").click()
        Select(driver.find_element_by_id("id_paciente")).select_by_visible_text("11111112 pac iente")
        driver.find_element_by_xpath("//option[@value='11111112']").click()
        driver.find_element_by_xpath("//input[@value='Solicitar Examen']").click()
        driver.find_element_by_link_text("Salir").click()
        driver.find_element_by_name("username").click()
        driver.find_element_by_xpath("//div[@id='header']/div/center").click()
        driver.find_element_by_xpath("//a[@id='registrarse']/b").click()
        driver.find_element_by_id("id_first_name").click()
        driver.find_element_by_id("id_first_name").clear()
        driver.find_element_by_id("id_first_name").send_keys("bio")
        driver.find_element_by_id("id_last_name").clear()
        driver.find_element_by_id("id_last_name").send_keys("analista")
        driver.find_element_by_id("id_email").clear()
        driver.find_element_by_id("id_email").send_keys("b@gmail.com")
        driver.find_element_by_id("id_rol").click()
        Select(driver.find_element_by_id("id_rol")).select_by_visible_text("Bioanalista")
        driver.find_element_by_xpath("//option[@value='bioanalista']").click()
        driver.find_element_by_id("id_ci").click()
        driver.find_element_by_id("id_ci").clear()
        driver.find_element_by_id("id_ci").send_keys("11111115")
        driver.find_element_by_xpath("//div[@id='cuerpoHeredado']/form/div[5]/label").click()
        driver.find_element_by_id("id_username").click()
        driver.find_element_by_id("id_username").clear()
        driver.find_element_by_id("id_username").send_keys("bioanalista")
        driver.find_element_by_id("id_passw").click()
        driver.find_element_by_id("id_passw").clear()
        driver.find_element_by_id("id_passw").send_keys("12345")
        driver.find_element_by_id("id_submit").click()
        driver.find_element_by_id("id_laboratorio").click()
        Select(driver.find_element_by_id("id_laboratorio")).select_by_visible_text("Laboratorio")
        #driver.find_element_by_xpath("//option[@value='1']").click()
        driver.find_element_by_id("id_submit").click()
        driver.find_element_by_name("username").click()
        driver.find_element_by_name("username").clear()
        driver.find_element_by_name("username").send_keys("bioanalista")
        driver.find_element_by_name("password").clear()
        driver.find_element_by_name("password").send_keys("12345")
        driver.find_element_by_xpath("//input[@value='Login']").click()
        driver.find_element_by_link_text("Ver Examenes").click()
        driver.find_element_by_xpath("//a[@id='add_medicion']/i").click()
        driver.find_element_by_id("id_tipo_examen").click()
        Select(driver.find_element_by_id("id_tipo_examen")).select_by_visible_text("colonoscopia")
        driver.find_element_by_xpath("//option[@value='colonoscopia']").click()
        driver.find_element_by_id("id_paciente").click()
        Select(driver.find_element_by_id("id_paciente")).select_by_visible_text("11111112 pac iente")
        driver.find_element_by_xpath("//option[@value='11111112']").click()
        driver.find_element_by_id("id_laboratorio").click()
        Select(driver.find_element_by_id("id_laboratorio")).select_by_visible_text("Laboratorio")
        #driver.find_element_by_xpath("//option[@value='1']").click()
        driver.find_element_by_xpath("//input[@value='Crear']").click()
        driver.find_element_by_name("medicion").click()
        driver.find_element_by_name("medicion").clear()
        driver.find_element_by_name("medicion").send_keys("3")
        driver.find_element_by_xpath("//input[@value='Crear']").click()
        driver.find_element_by_link_text("Solicitudes de Examen").click()
        driver.find_element_by_link_text("Salir").click()
    
    def is_element_present(self, how, what):
        try: self.driver.find_element(by=how, value=what)
        except NoSuchElementException as e: return False
        return True
    
    def is_alert_present(self):
        try: self.driver.switch_to_alert()
        except NoAlertPresentException as e: return False
        return True
    
    def close_alert_and_get_its_text(self):
        try:
            alert = self.driver.switch_to_alert()
            alert_text = alert.text
            if self.accept_next_alert:
                alert.accept()
            else:
                alert.dismiss()
            return alert_text
        finally: self.accept_next_alert = True
    
    def tearDown(self):
        self.driver.quit()
        self.assertEqual([], self.verificationErrors)

if __name__ == "__main__":
    unittest.main()
